In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import files

uploaded = files.upload()

Saving dashboard_dataset.csv to dashboard_dataset.csv

In [3]:
df = pd.read_csv(
    "dashboard_dataset.csv"
)

In [5]:
df.head()
df.shape
df.columns.tolist()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 33 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       7500 non-null   int64
 1   gender                    7500 non-null   int64
 2   daily_screen_time_hours   7500 non-null   float64
 3   social_media_hours        7500 non-null   float64
 4   gaming_hours              7500 non-null   float64
 5   work_study_hours          7500 non-null   float64
 6   sleep_hours               7500 non-null   float64
 7   notifications_per_day     7500 non-null   int64
 8   app_opens_per_day         7500 non-null   int64
 9   weekend_screen_time       7500 non-null   float64
 10  stress_level              7500 non-null   object
 11  academic_work_impact      7500 non-null   object
 12  addiction_level           7500 non-null   object
 13  addicted_label            7500 non-null   int64
 14  weekend_usage_difference  7500 non-null   float64
 15  sleep_deficit             7500 non-null   float64
 16  notification_intensity    7500 non-null   float64
 17  weekend_overuse           7500 non-null   float64
 18  DEI                       7500 non-null   float64
 19  DEI_Category              7500 non-null   object
 20  attention_score           7500 non-null   float64
 21  attention_category        7500 non-null   object
 22  addiction_level_num       7500 non-null   int64
 23  NDI                       7500 non-null   float64
 24  dependency_category       7500 non-null   object
 25  attention_inverse         7500 non-null   float64
 26  Aggression_Risk           7500 non-null   float64
 27  Aggression_Category       7500 non-null   object
 28  Wellbeing_Score           7500 non-null   float64
 29  Wellbeing_Category        7500 non-null   object
 30  Cluster                   7500 non-null   int64
 31  User_Segment              7500 non-null   object
 32  Recommendation            7500 non-null   object
dtypes: float64(16), int64(7), object(10)
memory usage: 1.9+ MB

In [8]:
#Generate KPIs
#Average DEI

avg_dei = round(
    df['DEI'].mean(),
    2
)

print(avg_dei)

#Average NDI

avg_ndi = round(
    df['NDI'].mean(),
    2
)

print(avg_ndi)

#Average Attention

avg_attention = round(
    df['attention_score'].mean(),
    2
)

print(avg_attention)

#Average Aggression

avg_aggression = round(
    df['Aggression_Risk'].mean(),
    2
)

print(avg_aggression)

#Average Wellbeing

avg_wellbeing = round(
    df['Wellbeing_Score'].mean(),
    2
)

print(avg_wellbeing)

47.94
51.02
67.02
48.41
57.39

In [12]:
#KPI Summary Table

kpi_table = pd.DataFrame({

    'Metric': [

        'Average DEI',

        'Average NDI',

        'Average Attention',

        'Average Aggression',

        'Average Wellbeing'

    ],

    'Value': [

        avg_dei,

        avg_ndi,

        avg_attention,

        avg_aggression,

        avg_wellbeing

    ]

})

kpi_table

               Metric  Value
0         Average DEI  47.94
1         Average NDI  51.02
2   Average Attention  67.02
3  Average Aggression  48.41
4   Average Wellbeing  57.39

In [13]:
kpi_table.to_csv(
    "kpi_summary.csv",
    index=False
)

In [14]:
#Wellbeing Category Summary

wellbeing_summary = (

    df[
        'Wellbeing_Category'
    ]

    .value_counts()

    .reset_index()

)

wellbeing_summary

  Wellbeing_Category  count
0            Average   5765
1          Excellent   1188
2               Poor    547

In [15]:
wellbeing_summary.to_csv(
    "wellbeing_summary.csv",
    index=False
)

In [16]:
#User Segment Summary

segment_summary = (

    df[
        'User_Segment'
    ]

    .value_counts()

    .reset_index()

)

segment_summary

  User_Segment  count
0      Healthy   3034
1    High-Risk   2233
2      At-Risk   2233

In [17]:
segment_summary.to_csv(
    "segment_summary.csv",
    index=False
)

In [18]:
#Dependency Category Summary

dependency_summary = (

    df[
        'dependency_category'
    ]

    .value_counts()

    .reset_index()

)

dependency_summary

  dependency_category  count
0            Moderate   4943
1                High   1440
2                 Low   1117

In [19]:
dependency_summary.to_csv(
    "dependency_summary.csv",
    index=False
)

In [20]:
#Aggression Category Summary

aggression_summary = (

    df[
        'Aggression_Category'
    ]

    .value_counts()

    .reset_index()

)

aggression_summary

  Aggression_Category  count
0            Moderate   5348
1                 Low   1238
2                High    914

In [21]:
aggression_summary.to_csv(
    "aggression_summary.csv",
    index=False
)

In [22]:
#Top Recommendations

recommendation_summary = (

    df[
        'Recommendation'
    ]

    .value_counts()

    .reset_index()

)

recommendation_summary.head(20)

                                       Recommendation  count
0                              Improve sleep schedule   2918
1                             Maintain current habits   2537
2                 Disable non-essential notifications    506
3   Disable non-essential notifications; Improve s...    339
4    Reduce daily screen time; Improve sleep schedule    249
5   Reduce daily screen time; Disable non-essentia...    210
6   Reduce daily screen time; Improve sleep schedu...    205
7   Disable non-essential notifications; Improve s...    195
8   Disable non-essential notifications; Practice ...    128
9   Reduce daily screen time; Improve sleep schedu...     61
10  Reduce daily screen time; Disable non-essentia...     38
11   Reduce daily screen time; Practice digital detox     33
12                           Reduce daily screen time     27
13  Reduce daily screen time; Disable non-essentia...     24
14     Improve sleep schedule; Practice digital detox     11
15  Reduce daily screen time; Improve sleep schedu...     10
16                             Practice digital detox      9

In [23]:
recommendation_summary.to_csv(
    "recommendation_summary.csv",
    index=False
)

In [24]:
#Correlation Export
numeric_df = df.select_dtypes(
    include=['number']
)

corr = numeric_df.corr()

corr

,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,...,notification_intensity,weekend_overuse,DEI,attention_score,addiction_level_num,NDI,attention_inverse,Aggression_Risk,Wellbeing_Score,Cluster
age,1.000000,0.017495,0.012767,0.000342,-0.026107,-0.017147,-0.007462,0.000387,-0.002276,0.015286,...,-0.005204,0.011443,0.008620,-0.008607,0.016920,0.007508,0.008607,0.009918,-0.010278,0.009125
gender,0.017495,1.000000,0.006968,-0.001151,-0.004499,-0.005200,-0.025167,0.003727,-0.006357,0.005832,...,0.000732,-0.003231,0.012958,-0.012489,0.008338,0.002797,0.012489,0.010594,-0.013629,-0.003225
daily_screen_time_hours,0.012767,0.006968,1.000000,0.010321,0.001140,0.003108,0.019343,0.000811,0.024448,0.964295,...,-0.572565,0.016720,0.695998,-0.824006,0.394220,0.401803,0.824006,0.750243,-0.738942,-0.344905
social_media_hours,0.000342,-0.001151,0.010321,1.000000,-0.000902,-0.002580,0.005947,-0.008593,-0.000371,0.011404,...,-0.008654,0.005651,0.498649,-0.411069,0.331725,0.101849,0.411069,0.378348,-0.388816,-0.174473
gaming_hours,-0.026107,-0.004499,0.001140,-0.000902,1.000000,0.004384,-0.002874,0.015563,-0.009917,-0.006282,...,0.013032,-0.027849,0.193451,-0.195621,0.000872,0.003935,0.195621,0.143196,-0.152822,-0.052163
work_study_hours,-0.017147,-0.005200,0.003108,-0.002580,0.004384,1.000000,-0.027150,-0.017518,-0.021676,0.004667,...,-0.026276,0.006354,0.014543,-0.011870,0.003789,-0.022086,0.011870,-0.001242,-0.004956,0.010101
sleep_hours,-0.007462,-0.025167,0.019343,0.005947,-0.002874,-0.027150,1.000000,0.016273,0.005692,0.018933,...,0.007457,0.001384,-0.423370,0.322852,0.030698,0.028196,-0.322852,-0.255283,0.385743,0.084315
notifications_per_day,0.000387,0.003727,0.000811,-0.008593,0.015563,-0.017518,0.016273,1.000000,0.004598,-0.002199,...,0.728163,-0.011241,-0.011295,0.006472,-0.009883,0.610097,-0.006472,0.291447,-0.217646,-0.109809
app_opens_per_day,-0.002276,-0.006357,0.024448,-0.000371,-0.009917,-0.021676,0.005692,0.004598,1.000000,0.021069,...,-0.006362,-0.009053,0.011237,-0.015754,0.010643,0.631082,0.015754,0.317932,-0.243939,-0.114361
weekend_screen_time,0.015286,0.005832,0.964295,0.011404,-0.006282,0.004667,0.018933,-0.002199,0.021069,1.000000,...,-0.554402,0.280915,0.722389,-0.810965,0.379028,0.383736,0.810965,0.745550,-0.736834,-0.342613
addicted_label,0.004220,-0.003499,0.577112,0.414244,0.008485,0.001103,0.035496,-0.000660,0.011041,0.555426,...,-0.328989,0.005571,0.592824,-0.633538,0.706638,0.380406,0.633538,0.631609,-0.613879,-0.450449
weekend_usage_difference,0.011443,-0.003231,0.016720,0.005651,-0.027849,0.006354,0.001384,-0.011241,-0.009053,0.280915,...,-0.018182,1.000000,0.205099,-0.075620,0.002373,-0.007332,0.075620,0.095958,-0.104008,-0.043604
sleep_deficit,0.005502,0.022921,-0.015759,-0.005861,0.005655,0.025927,-0.986882,-0.018992,-0.004106,-0.015679,...,-0.012255,-0.002084,0.432149,-0.325766,-0.029392,-0.027524,0.325766,0.259749,-0.389018,-0.087102
notification_intensity,-0.005204,0.000732,-0.572565,-0.008654,0.013032,-0.026276,0.007457,0.728163,-0.006362,-0.554402,...,1.000000,-0.018182,-0.408346,0.477497,-0.207888,0.224865,-0.477497,-0.213066,0.262377,0.127819
weekend_overuse,0.011443,-0.003231,0.016720,0.005651,-0.027849,0.006354,0.001384,-0.011241,-0.009053,0.280915,...,-0.018182,1.000000,0.205099,-0.075620,0.002373,-0.007332,0.075620,0.095958,-0.104008,-0.043604
DEI,0.008620,0.012958,0.695998,0.498649,0.193451,0.014543,-0.423370,-0.011295,0.011237,0.722389,...,-0.408346,0.205099,1.000000,-0.973235,0.424892,0.316313,0.973235,0.870210,-0.928560,-0.383153
attention_score,-0.008607,-0.012489,-0.824006,-0.411069,-0.195621,-0.011870,0.322852,0.006472,-0.015754,-0.810965,...,0.477497,-0.075620,-0.973235,1.000000,-0.449250,-0.363252,-1.000000,-0.894100,0.935953,0.397292
addiction_level_num,0.016920,0.008338,0.394220,0.331725,0.000872,0.003789,0.030698,-0.009883,0.010643,0.379028,...,-0.207888,0.002373,0.424892,-0.449250,1.000000,0.419160,0.449250,0.522370,-0.491792,-0.297428
NDI,0.007508,0.002797,0.401803,0.101849,0.003935,-0.022086,0.028196,0.610097,0.631082,0.383736,...,0.224865,-0.007332,0.316313,-0.363252,0.419160,1.000000,0.363252,0.735677,-0.632277,-0.321854
attention_inverse,0.008607,0.012489,0.824006,0.411069,0.195621,0.011870,-0.322852,-0.006472,0.015754,0.810965,...,-0.477497,0.075620,0.973235,-1.000000,0.449250,0.363252,1.000000,0.894100,-0.935953,-0.397292
Aggression_Risk,0.009918,0.010594,0.750243,0.378348,0.143196,-0.001242,-0.255283,0.291447,0.317932,0.745550,...,-0.213066,0.095958,0.870210,-0.894100,0.522370,0.735677,0.894100,1.000000,-0.985600,-0.440672
Wellbeing_Score,-0.010278,-0.013629,-0.738942,-0.388816,-0.152822,-0.004956,0.385743,-0.217646,-0.243939,-0.736834,...,0.262377,-0.104008,-0.928560,0.935953,-0.491792,-0.632277,-0.935953,-0.985600,1.000000,0.431619
Cluster,0.009125,-0.003225,-0.344905,-0.174473,-0.052163,0.010101,0.084315,-0.109809,-0.114361,-0.342613,...,0.127819,-0.043604,-0.383153,0.397292,-0.297428,-0.321854,-0.397292,-0.440672,0.431619,1.000000

In [25]:
corr.to_csv(
    "correlation_matrix.csv"
)

In [26]:
#Export Dashboard Dataset

df.to_csv(
    "final_dashboard_dataset.csv",
    index=False
)

In [27]:
#Download Files

from google.colab import files

files.download(
    "final_dashboard_dataset.csv"
)